version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-admlinux
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_facultad
      
      # Usuario administrador
      MYSQL_USER: admlinux
      MYSQL_PASSWORD: blabla
      
      # Usuario de solo lectura
      MYSQL_READONLY_USER: usuario_lectura
      MYSQL_READONLY_PASSWORD: bla
      
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
